name: "SuperFly"
author: "Teddy"
description: "Manage fly mode for players"
version: "1.1"
api-version: "1.13"
main: "io.github.twieteddy.superfly.SuperFlyPlugin"

commands:
  fly:
    description: Toggle fly mode
  flyspeed:
    description: Modify fly speed